import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
    console.log("开始初始化默认数据...")

    const defaultConfigs = [
        {
            city: "北京",
            base_lower: 5360,
            base_upper: 31884,
            housing_fund_base_lower: 2320,
            housing_fund_base_upper: 31884,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.10,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            unemployment_personal_rate: 0.002,
            unemployment_company_rate: 0.008,
            injury_personal_rate: 0,
            injury_company_rate: 0.004,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.008,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "上海",
            base_lower: 7310,
            base_upper: 36549,
            housing_fund_base_lower: 2590,
            housing_fund_base_upper: 36549,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.10,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            injury_personal_rate: 0,
            injury_company_rate: 0.0016,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.01,
            housing_fund_personal_rate: 0.07,
            housing_fund_company_rate: 0.07,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "广州",
            base_lower: 2300,
            base_upper: 38082,
            housing_fund_base_lower: 2300,
            housing_fund_base_upper: 38082,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.14,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.065,
            unemployment_personal_rate: 0.002,
            unemployment_company_rate: 0.0048,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.0085,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "深圳",
            base_lower: 2360,
            base_upper: 31938,
            housing_fund_base_lower: 2360,
            housing_fund_base_upper: 31938,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.13,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.062,
            unemployment_personal_rate: 0.003,
            unemployment_company_rate: 0.007,
            injury_personal_rate: 0,
            injury_company_rate: 0.0014,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.0045,
            housing_fund_personal_rate: 0.13,
            housing_fund_company_rate: 0.13,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "杭州",
            base_lower: 3957,
            base_upper: 19783,
            housing_fund_base_lower: 1860,
            housing_fund_base_upper: 19783,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.14,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.105,
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.008,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "成都",
            base_lower: 2966,
            base_upper: 20307,
            housing_fund_base_lower: 1650,
            housing_fund_base_upper: 20307,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.075,
            unemployment_personal_rate: 0.004,
            unemployment_company_rate: 0.006,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.006,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "南京",
            base_lower: 4494,
            base_upper: 24042,
            housing_fund_base_lower: 1620,
            housing_fund_base_upper: 24042,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.09,
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.008,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "武汉",
            base_lower: 3739.8,
            base_upper: 18699,
            housing_fund_base_lower: 1750,
            housing_fund_base_upper: 18699,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.08,
            unemployment_personal_rate: 0.003,
            unemployment_company_rate: 0.007,
            injury_personal_rate: 0,
            injury_company_rate: 0.0024,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.005,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "西安",
            base_lower: 3632,
            base_upper: 18159,
            housing_fund_base_lower: 1680,
            housing_fund_base_upper: 18159,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.07,
            unemployment_personal_rate: 0.003,
            unemployment_company_rate: 0.007,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.005,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "苏州",
            base_lower: 4250,
            base_upper: 24042,
            housing_fund_base_lower: 1620,
            housing_fund_base_upper: 24042,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.09,
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.008,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
    ]

    for (const config of defaultConfigs) {
        await prisma.socialSecurityConfig.upsert({
            where: { city: config.city },
            update: {},
            create: config,
        })
        console.log(`✓ 已创建/更新 ${config.city} 的配置`)
    }

    console.log("✅ 默认数据初始化完成！")
}

main()
    .catch((e) => {
        console.error("❌ 初始化失败:", e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })

