import { PrismaClient } from "@prisma/client"
import bcrypt from "bcryptjs"

const prisma = new PrismaClient()

async function main() {
    // 创建默认超级管理员账户
    const adminPassword = await bcrypt.hash("admin123", 10)
    const admin = await prisma.user.upsert({
        where: { username: "admin" },
        update: {},
        create: {
            username: "admin",
            password: adminPassword,
            role: "admin",
            name: "系统管理员",
            email: "admin@example.com",
            is_active: true,
        },
    })
    console.log("✅ 创建默认管理员账户:", admin.username)

    // 创建测试用户账户
    const userPassword = await bcrypt.hash("user123", 10)
    const user = await prisma.user.upsert({
        where: { username: "user" },
        update: {},
        create: {
            username: "user",
            password: userPassword,
            role: "user",
            name: "测试用户",
            email: "user@example.com",
            is_active: true,
        },
    })
    console.log("✅ 创建测试用户账户:", user.username)
    console.log("开始初始化默认数据...")

    const defaultConfigs = [
        {
            city: "北京",
            base_lower: 7162,
            base_upper: 35811,
            housing_fund_base_lower: 2540,
            housing_fund_base_upper: 35811,
            // 养老保险
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 7162,
            pension_base_upper: 35811,
            // 医疗保险
            medical_personal_rate: 0.02,
            medical_company_rate: 0.09,
            medical_personal_fixed: 3,
            medical_company_fixed: 0,
            medical_base_lower: 7162,
            medical_base_upper: 35811,
            // 失业保险
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            unemployment_base_lower: 7162,
            unemployment_base_upper: 35811,
            // 工伤保险
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            injury_base_lower: 7162,
            injury_base_upper: 35811,
            // 生育保险
            maternity_personal_rate: 0,
            maternity_company_rate: 0.008,
            maternity_base_lower: 7162,
            maternity_base_upper: 35811,
            // 住房公积金
            housing_fund_personal_rate: 0.05,
            housing_fund_company_rate: 0.05,
            housing_fund_base_lower_new: 2540,
            housing_fund_base_upper_new: 35811,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "天津",
            base_lower: 5124,
            base_upper: 25065,
            housing_fund_base_lower: 2320,
            housing_fund_base_upper: 26451,
            // 养老保险
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 5124,
            pension_base_upper: 25065,
            // 医疗保险
            medical_personal_rate: 0.02,
            medical_company_rate: 0.10,
            medical_personal_fixed: 22,
            medical_company_fixed: 0,
            medical_base_lower: 5124,
            medical_base_upper: 25065,
            // 失业保险
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            unemployment_base_lower: 5124,
            unemployment_base_upper: 25065,
            // 工伤保险
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            injury_base_lower: 5124,
            injury_base_upper: 25065,
            // 生育保险
            maternity_personal_rate: 0,
            maternity_company_rate: 0.005,
            maternity_base_lower: 5124,
            maternity_base_upper: 25065,
            // 住房公积金
            housing_fund_personal_rate: 0.05,
            housing_fund_company_rate: 0.05,
            housing_fund_base_lower_new: 2320,
            housing_fund_base_upper_new: 26451,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "郑州",
            base_lower: 3831,
            base_upper: 19155,
            housing_fund_base_lower: 2100,
            housing_fund_base_upper: 27520,
            // 养老保险
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 3831,
            pension_base_upper: 19155,
            // 医疗保险
            medical_personal_rate: 0.02,
            medical_company_rate: 0.07,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 3831,
            medical_base_upper: 19155,
            // 失业保险
            unemployment_personal_rate: 0.003,
            unemployment_company_rate: 0.007,
            unemployment_base_lower: 3831,
            unemployment_base_upper: 19155,
            // 工伤保险
            injury_personal_rate: 0,
            injury_company_rate: 0.0032,
            injury_base_lower: 3831,
            injury_base_upper: 19155,
            // 生育保险
            maternity_personal_rate: 0,
            maternity_company_rate: 0.01,
            maternity_base_lower: 3831,
            maternity_base_upper: 19155,
            // 住房公积金
            housing_fund_personal_rate: 0.05,
            housing_fund_company_rate: 0.05,
            housing_fund_base_lower_new: 2100,
            housing_fund_base_upper_new: 27520,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "上海",
            base_lower: 7310,
            base_upper: 36549,
            housing_fund_base_lower: 2590,
            housing_fund_base_upper: 36549,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 7310,
            pension_base_upper: 36549,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.10,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 7310,
            medical_base_upper: 36549,
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            unemployment_base_lower: 7310,
            unemployment_base_upper: 36549,
            injury_personal_rate: 0,
            injury_company_rate: 0.0016,
            injury_base_lower: 7310,
            injury_base_upper: 36549,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.01,
            maternity_base_lower: 7310,
            maternity_base_upper: 36549,
            housing_fund_personal_rate: 0.07,
            housing_fund_company_rate: 0.07,
            housing_fund_base_lower_new: 2590,
            housing_fund_base_upper_new: 36549,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "广州",
            base_lower: 2300,
            base_upper: 38082,
            housing_fund_base_lower: 2300,
            housing_fund_base_upper: 38082,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.14,
            pension_base_lower: 2300,
            pension_base_upper: 38082,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.065,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 2300,
            medical_base_upper: 38082,
            unemployment_personal_rate: 0.002,
            unemployment_company_rate: 0.0048,
            unemployment_base_lower: 2300,
            unemployment_base_upper: 38082,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            injury_base_lower: 2300,
            injury_base_upper: 38082,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.0085,
            maternity_base_lower: 2300,
            maternity_base_upper: 38082,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_base_lower_new: 2300,
            housing_fund_base_upper_new: 38082,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "深圳",
            base_lower: 2360,
            base_upper: 31938,
            housing_fund_base_lower: 2360,
            housing_fund_base_upper: 31938,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.13,
            pension_base_lower: 2360,
            pension_base_upper: 31938,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.062,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 2360,
            medical_base_upper: 31938,
            unemployment_personal_rate: 0.003,
            unemployment_company_rate: 0.007,
            unemployment_base_lower: 2360,
            unemployment_base_upper: 31938,
            injury_personal_rate: 0,
            injury_company_rate: 0.0014,
            injury_base_lower: 2360,
            injury_base_upper: 31938,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.0045,
            maternity_base_lower: 2360,
            maternity_base_upper: 31938,
            housing_fund_personal_rate: 0.13,
            housing_fund_company_rate: 0.13,
            housing_fund_base_lower_new: 2360,
            housing_fund_base_upper_new: 31938,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "杭州",
            base_lower: 3957,
            base_upper: 19783,
            housing_fund_base_lower: 1860,
            housing_fund_base_upper: 19783,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.14,
            pension_base_lower: 3957,
            pension_base_upper: 19783,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.105,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 3957,
            medical_base_upper: 19783,
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            unemployment_base_lower: 3957,
            unemployment_base_upper: 19783,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            injury_base_lower: 3957,
            injury_base_upper: 19783,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.008,
            maternity_base_lower: 3957,
            maternity_base_upper: 19783,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_base_lower_new: 1860,
            housing_fund_base_upper_new: 19783,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "成都",
            base_lower: 4511,
            base_upper: 22555,
            housing_fund_base_lower: 2100,
            housing_fund_base_upper: 31362,
            // 养老保险
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 4511,
            pension_base_upper: 22555,
            // 医疗保险
            medical_personal_rate: 0.02,
            medical_company_rate: 0.0755,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 4511,
            medical_base_upper: 22555,
            // 失业保险
            unemployment_personal_rate: 0.004,
            unemployment_company_rate: 0.006,
            unemployment_base_lower: 4511,
            unemployment_base_upper: 22555,
            // 工伤保险
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            injury_base_lower: 4511,
            injury_base_upper: 22555,
            // 生育保险
            maternity_personal_rate: 0,
            maternity_company_rate: 0.0075,
            maternity_base_lower: 4511,
            maternity_base_upper: 22555,
            // 住房公积金
            housing_fund_personal_rate: 0.05,
            housing_fund_company_rate: 0.05,
            housing_fund_base_lower_new: 2100,
            housing_fund_base_upper_new: 31362,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "南京",
            base_lower: 4494,
            base_upper: 24042,
            housing_fund_base_lower: 1620,
            housing_fund_base_upper: 24042,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 4494,
            pension_base_upper: 24042,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.09,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 4494,
            medical_base_upper: 24042,
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            unemployment_base_lower: 4494,
            unemployment_base_upper: 24042,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            injury_base_lower: 4494,
            injury_base_upper: 24042,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.008,
            maternity_base_lower: 4494,
            maternity_base_upper: 24042,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_base_lower_new: 1620,
            housing_fund_base_upper_new: 24042,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "武汉",
            base_lower: 3739.8,
            base_upper: 18699,
            housing_fund_base_lower: 1750,
            housing_fund_base_upper: 18699,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 3739.8,
            pension_base_upper: 18699,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.08,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 3739.8,
            medical_base_upper: 18699,
            unemployment_personal_rate: 0.003,
            unemployment_company_rate: 0.007,
            unemployment_base_lower: 3739.8,
            unemployment_base_upper: 18699,
            injury_personal_rate: 0,
            injury_company_rate: 0.0024,
            injury_base_lower: 3739.8,
            injury_base_upper: 18699,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.005,
            maternity_base_lower: 3739.8,
            maternity_base_upper: 18699,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_base_lower_new: 1750,
            housing_fund_base_upper_new: 18699,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "西安",
            base_lower: 4559,
            base_upper: 23250,
            housing_fund_base_lower: 2160,
            housing_fund_base_upper: 30918,
            // 养老保险
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 4559,
            pension_base_upper: 23250,
            // 医疗保险
            medical_personal_rate: 0.02,
            medical_company_rate: 0.08,
            medical_personal_fixed: 1.6,
            medical_company_fixed: 0,
            medical_base_lower: 4990,
            medical_base_upper: 24948,
            // 失业保险
            unemployment_personal_rate: 0.003,
            unemployment_company_rate: 0.007,
            unemployment_base_lower: 4559,
            unemployment_base_upper: 23250,
            // 工伤保险
            injury_personal_rate: 0,
            injury_company_rate: 0.0032,
            injury_base_lower: 4559,
            injury_base_upper: 23250,
            // 生育保险
            maternity_personal_rate: 0,
            maternity_company_rate: 0.064,
            maternity_base_lower: 4990,
            maternity_base_upper: 24948,
            // 住房公积金
            housing_fund_personal_rate: 0.05,
            housing_fund_company_rate: 0.05,
            housing_fund_base_lower_new: 2160,
            housing_fund_base_upper_new: 30918,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "太原",
            base_lower: 4198,
            base_upper: 20991,
            housing_fund_base_lower: 2150,
            housing_fund_base_upper: 28251,
            // 养老保险
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 4198,
            pension_base_upper: 20991,
            // 医疗保险
            medical_personal_rate: 0.02,
            medical_company_rate: 0.084,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 4198,
            medical_base_upper: 20991,
            // 失业保险
            unemployment_personal_rate: 0.003,
            unemployment_company_rate: 0.007,
            unemployment_base_lower: 4198,
            unemployment_base_upper: 20991,
            // 工伤保险
            injury_personal_rate: 0,
            injury_company_rate: 0.0046,
            injury_base_lower: 4198,
            injury_base_upper: 20991,
            // 生育保险
            maternity_personal_rate: 0,
            maternity_company_rate: 0,
            maternity_base_lower: 4198,
            maternity_base_upper: 20991,
            // 住房公积金
            housing_fund_personal_rate: 0.05,
            housing_fund_company_rate: 0.05,
            housing_fund_base_lower_new: 2150,
            housing_fund_base_upper_new: 28251,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
        {
            city: "苏州",
            base_lower: 4250,
            base_upper: 24042,
            housing_fund_base_lower: 1620,
            housing_fund_base_upper: 24042,
            pension_personal_rate: 0.08,
            pension_company_rate: 0.16,
            pension_base_lower: 4250,
            pension_base_upper: 24042,
            medical_personal_rate: 0.02,
            medical_company_rate: 0.09,
            medical_personal_fixed: 0,
            medical_company_fixed: 0,
            medical_base_lower: 4250,
            medical_base_upper: 24042,
            unemployment_personal_rate: 0.005,
            unemployment_company_rate: 0.005,
            unemployment_base_lower: 4250,
            unemployment_base_upper: 24042,
            injury_personal_rate: 0,
            injury_company_rate: 0.002,
            injury_base_lower: 4250,
            injury_base_upper: 24042,
            maternity_personal_rate: 0,
            maternity_company_rate: 0.008,
            maternity_base_lower: 4250,
            maternity_base_upper: 24042,
            housing_fund_personal_rate: 0.12,
            housing_fund_company_rate: 0.12,
            housing_fund_base_lower_new: 1620,
            housing_fund_base_upper_new: 24042,
            housing_fund_protection_enabled: false,
            created_by: "system",
        },
    ]

    for (const config of defaultConfigs) {
        await prisma.socialSecurityConfig.upsert({
            where: { city: config.city },
            update: {},
            create: config,
        })
        console.log(`✓ 已创建/更新 ${config.city} 的配置`)
    }

    console.log("✅ 默认数据初始化完成！")
}

main()
    .catch((e) => {
        console.error("❌ 初始化失败:", e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })

